/**
 * One-click looks. Each theme is a shallow patch over the profile config —
 * applying one only touches the keys listed here, so your links, bio, avatar
 * and Discord settings are never disturbed.
 */
export const THEMES = [
  {
    id: 'midnight',
    name: 'Midnight',
    swatch: ['#a855f7', '#060409'],
    patch: {
      accent: '#a855f7',
      bg_color: '#060409',
      card_opacity: 0.55,
      card_blur: 24,
      icon_style: 'mono',
      card_border: 'none',
      entrance: 'rise',
      particle_style: 'dust',
      trail_style: 'glow',
      trail_color: '',
    },
  },
  {
    id: 'cyber',
    name: 'Cyber',
    swatch: ['#22d3ee', '#03080d'],
    patch: {
      accent: '#22d3ee',
      bg_color: '#03080d',
      card_opacity: 0.4,
      card_blur: 18,
      icon_style: 'mono',
      card_border: 'gradient',
      entrance: 'glitch',
      particle_style: 'matrix',
      trail_style: 'comet',
      trail_color: '',
    },
  },
  {
    id: 'frost',
    name: 'Frost',
    swatch: ['#7dd3fc', '#070b12'],
    patch: {
      accent: '#7dd3fc',
      bg_color: '#070b12',
      card_opacity: 0.5,
      card_blur: 28,
      icon_style: 'mono',
      card_border: 'glow',
      entrance: 'blur',
      particle_style: 'snow',
      trail_style: 'sparkle',
      trail_color: '',
    },
  },
  {
    id: 'blood',
    name: 'Blood',
    swatch: ['#ef4444', '#0a0304'],
    patch: {
      accent: '#ef4444',
      bg_color: '#0a0304',
      card_opacity: 0.6,
      card_blur: 20,
      icon_style: 'mono',
      card_border: 'beam',
      entrance: 'zoom',
      particle_style: 'dust',
      trail_style: 'glow',
      trail_color: '',
    },
  },
  {
    id: 'sakura',
    name: 'Sakura',
    swatch: ['#f472b6', '#0d0710'],
    patch: {
      accent: '#f472b6',
      bg_color: '#0d0710',
      card_opacity: 0.5,
      card_blur: 26,
      icon_style: 'mono',
      card_border: 'glow',
      entrance: 'fade',
      particle_style: 'snow',
      trail_style: 'sparkle',
      trail_color: '',
    },
  },
  {
    id: 'gold',
    name: 'Gold',
    swatch: ['#f59e0b', '#080704'],
    patch: {
      accent: '#f59e0b',
      bg_color: '#080704',
      card_opacity: 0.62,
      card_blur: 22,
      icon_style: 'mono',
      card_border: 'gradient',
      entrance: 'rise',
      particle_style: 'dust',
      trail_style: 'glow',
      trail_color: '',
    },
  },
  {
    id: 'storm',
    name: 'Storm',
    swatch: ['#64748b', '#05070a'],
    patch: {
      accent: '#94a3b8',
      bg_color: '#05070a',
      card_opacity: 0.45,
      card_blur: 16,
      icon_style: 'mono',
      card_border: 'none',
      entrance: 'fade',
      particle_style: 'rain',
      trail_style: 'comet',
      trail_color: '',
    },
  },
  {
    id: 'mono',
    name: 'Mono',
    swatch: ['#ffffff', '#000000'],
    patch: {
      accent: '#ffffff',
      bg_color: '#000000',
      card_opacity: 0.35,
      card_blur: 14,
      icon_style: 'mono',
      card_border: 'none',
      entrance: 'fade',
      particle_style: 'dust',
      trail_style: 'glow',
      trail_color: '',
    },
  },
]
